name: Autograph
version: '${project.version}'
main: by.quaks.autograph.Autograph
api-version: 1.19
commands:
  autograph:
    description: Подписать предмет
    usage: /autograph
    aliases:
      - aph